export const FoodApi = [
    {
      "food_id": 1,
      "food_name": "Bánh Mì Chảo(Hà Nội)",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "25000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Bánh Mì",
      "food_src": "banhmi/banhmi1.png"
    },
    {
      "food_id": 2,
      "food_name": "Bánh Mì Cay",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "16000.00",
      "food_discount": "3000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Chay",
      "food_category": "Bánh Mì",
      "food_src": "banhmi/banhmi2.png"
    },
    {
      "food_id": 3,
      "food_name": "Bánh Mì Bột Lọc",
      "food_star": "4.5",
      "food_vote": "500",
      "food_price": "17000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Bánh Mì",
      "food_src": "banhmi/banhmi3.png"
    },
    {
      "food_id": 4,
      "food_name": "Bánh Mì Chả Cá",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "26000.00",
      "food_discount": "2000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Bánh Mì",
      "food_src": "banhmi/banhmi4.png"
    },
    {
      "food_id": 5,
      "food_name": "Bánh Mì Ép",
      "food_star": "4",
      "food_vote": "500",
      "food_price": "20000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "normal",
      "food_type": "Mặn",
      "food_category": "Bánh Mì",
      "food_src": "banhmi/banhmi5.png"
    },
    {
      "food_id": 6,
      "food_name": "Bánh Mì Gà Xé",
      "food_star": "4",
      "food_vote": "500",
      "food_price": "25000.00",
      "food_discount": "2000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "new dishes",
      "food_type": "Mặn",
      "food_category": "Bánh Mì",
      "food_src": "banhmi/banhmi6.png"
    },
    {
      "food_id": 7,
      "food_name": "Bánh Mì Đầu Nhọn",
      "food_star": "4.5",
      "food_vote": "500",
      "food_price": "15000.00",
      "food_discount": "3000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "seasonal dishes online only",
      "food_type": "Mặn",
      "food_category": "Bánh Mì",
      "food_src": "banhmi/banhmi7.png"
    },
    {
      "food_id": 8,
      "food_name": "Bánh Mì Xíu Mại",
      "food_star": "4.5",
      "food_vote": "100",
      "food_price": "15000.00",
      "food_discount": "3000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "new dishes",
      "food_type": "Mặn",
      "food_category": "Bánh Mì",
      "food_src": "banhmi/banhmi8.png"
    },
    {
      "food_id": 9,
      "food_name": "Bún Riêu Cua",
      "food_star": "4.5",
      "food_vote": "600",
      "food_price": "25000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "new dishes",
      "food_type": "Mặn",
      "food_category": "Bún",
      "food_src": "bun/bun1.png"
    },
    {
      "food_id": 10,
      "food_name": "Bún Bò Huế",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "37000.00",
      "food_discount": "5000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Bún",
      "food_src": "bun/bun2.png"
    },
    {
      "food_id": 11,
      "food_name": "Bún Bò Giò Heo",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "40000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Bún",
      "food_src": "bun/bun3.png"
    },
    {
      "food_id": 12,
      "food_name": "Bún Mắm",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "35000.00",
      "food_discount": "4000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "new dishes",
      "food_type": "Mặn",
      "food_category": "Bún",
      "food_src": "bun/bun4.png"
    },
    {
      "food_id": 13,
      "food_name": "Bún Cá",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "30000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Bún",
      "food_src": "bun/bun5.png"
    },
    {
      "food_id": 14,
      "food_name": "Bún Ốc",
      "food_star": "4",
      "food_vote": "400",
      "food_price": "35000.00",
      "food_discount": "5000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "seasonal dishes",
      "food_type": "Mặn",
      "food_category": "Bún",
      "food_src": "bun/bun6.png"
    },
    {
      "food_id": 15,
      "food_name": "Phở Bò",
      "food_star": "4",
      "food_vote": "699",
      "food_price": "37000.00",
      "food_discount": "5000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Phở",
      "food_src": "pho/pho1.png"
    },
    {
      "food_id": 16,
      "food_name": "Phở Cuốn",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "32000.00",
      "food_discount": "0.00",
      "food_desc": "3 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Phở",
      "food_src": "pho/pho2.png"
    },
    {
      "food_id": 17,
      "food_name": "Phở Gà",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "45000.00",
      "food_discount": "5000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Phở",
      "food_src": "pho/pho3.png"
    },
    {
      "food_id": 18,
      "food_name": "Phở Xào",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "25000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Phở",
      "food_src": "pho/pho4.png"
    },
    {
      "food_id": 19,
      "food_name": "Phở Khô",
      "food_star": "4",
      "food_vote": "999",
      "food_price": "27000.00",
      "food_discount": "5000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "normal",
      "food_type": "Mặn",
      "food_category": "Phở",
      "food_src": "pho/pho5.png"
    },
    {
      "food_id": 20,
      "food_name": "Phở Trộn",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "32000.00",
      "food_discount": "2000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Phở",
      "food_src": "pho/pho6.png"
    },
    {
      "food_id": 21,
      "food_name": "Phở Chiên Phồng",
      "food_star": "4",
      "food_vote": "699",
      "food_price": "25000.00",
      "food_discount": "3000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Phở",
      "food_src": "pho/pho7.png"
    },
    {
      "food_id": 22,
      "food_name": "Phở Chua",
      "food_star": "4.5",
      "food_vote": "499",
      "food_price": "25000.00",
      "food_discount": "2000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "seasonal dishes",
      "food_type": "Mặn",
      "food_category": "Phở",
      "food_src": "pho/pho8.png"
    },
    {
      "food_id": 23,
      "food_name": "Phở Chay",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "20000.00",
      "food_discount": "2000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Chay",
      "food_category": "Phở",
      "food_src": "pho/pho9.png"
    },
    {
      "food_id": 24,
      "food_name": "Phở Bò Sốt Vang",
      "food_star": "4.5",
      "food_vote": "699",
      "food_price": "40000.00",
      "food_discount": "4000.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Mặn",
      "food_category": "Phở",
      "food_src": "pho/pho10.png"
    },
    {
      "food_id": 25,
      "food_name": "Khoai Tây Nướng",
      "food_star": "3.5",
      "food_vote": "699",
      "food_price": "15000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "new dishes seasonal dishes",
      "food_type": "Chay",
      "food_category": "Món Phụ",
      "food_src": "mp/mp1.png"
    },
    {
      "food_id": 26,
      "food_name": "Khoai Tây Chiên",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "9000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Chay",
      "food_category": "Món Phụ",
      "food_src": "mp/mp2.jpg"
    },
    {
      "food_id": 27,
      "food_name": "Đậu nướng",
      "food_star": "4",
      "food_vote": "200",
      "food_price": "6000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "normal",
      "food_type": "Chay",
      "food_category": "Món Phụ",
      "food_src": "mp/mp3.png"
    },
    {
      "food_id": 28,
      "food_name": "Cải Bắp",
      "food_star": "4",
      "food_vote": "100",
      "food_price": "12000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "new dishes",
      "food_type": "Chay",
      "food_category": "Món Phụ",
      "food_src": "mp/mp4.png"
    },
    {
      "food_id": 29,
      "food_name": "Súp Lơ Trắng",
      "food_star": "3.5",
      "food_vote": "299",
      "food_price": "20000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "new dishes",
      "food_type": "Chay",
      "food_category": "Món Phụ",
      "food_src": "mp/mp5.png"
    },
    {
      "food_id": 30,
      "food_name": "Chè Vải Hạt Sen",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "15000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Chay",
      "food_category": "Tráng Miệng",
      "food_src": "tm/tm1.png"
    },
    {
      "food_id": 31,
      "food_name": "Bánh Chuối Nướng",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "9000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Chay",
      "food_category": "Tráng Miệng",
      "food_src": "tm/tm2.png"
    },
    {
      "food_id": 32,
      "food_name": "Bánh Da Lợn",
      "food_star": "4.5",
      "food_vote": "50",
      "food_price": "9000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "new dishes",
      "food_type": "Chay",
      "food_category": "Tráng Miệng",
      "food_src": "tm/tm3.png"
    },
    {
      "food_id": 33,
      "food_name": "Sương Sáo",
      "food_star": "3",
      "food_vote": "599",
      "food_price": "17000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "seasonal dishes online only",
      "food_type": "Chay",
      "food_category": "Tráng Miệng",
      "food_src": "tm/tm4.png"
    },
    {
      "food_id": 34,
      "food_name": "Chè Dừa Dầm",
      "food_star": "4",
      "food_vote": "199",
      "food_price": "20000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "normal",
      "food_type": "Chay",
      "food_category": "Tráng Miệng",
      "food_src": "tm/tm5.png"
    },
    {
      "food_id": 35,
      "food_name": "Bánh Chuối Hấp",
      "food_star": "4",
      "food_vote": "299",
      "food_price": "12000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "normal",
      "food_type": "Chay",
      "food_category": "Tráng Miệng",
      "food_src": "tm/tm6.png"
    },
    {
      "food_id": 36,
      "food_name": "Chè 3 Màu",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "15000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "normal",
      "food_type": "Chay",
      "food_category": "Tráng Miệng",
      "food_src": "tm/tm7.png"
    },
    {
      "food_id": 37,
      "food_name": "Cà Phê",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "19000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Chay",
      "food_category": "Thức Uống",
      "food_src": "tu/tu1.png"
    },
    {
      "food_id": 38,
      "food_name": "Trà Trái Cây",
      "food_star": "4.5",
      "food_vote": "999",
      "food_price": "25000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Chay",
      "food_category": "Thức Uống",
      "food_src": "tu/tu2.png"
    },
    {
      "food_id": 39,
      "food_name": "Nước Ép",
      "food_star": "4.5",
      "food_vote": "599",
      "food_price": "25000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "new dishes seasonal dishes",
      "food_type": "Chay",
      "food_category": "Thức Uống",
      "food_src": "tu/tu3.png"
    },
    {
      "food_id": 40,
      "food_name": "Tiger",
      "food_star": "4",
      "food_vote": "999",
      "food_price": "20000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Chay",
      "food_category": "Thức Uống",
      "food_src": "tu/tu4.png"
    },
    {
      "food_id": 41,
      "food_name": "Heineken",
      "food_star": "3.5",
      "food_vote": "999",
      "food_price": "25000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "seasonal dishes best seller",
      "food_type": "Chay",
      "food_category": "Thức Uống",
      "food_src": "tu/tu5.png"
    },
    {
      "food_id": 42,
      "food_name": "Nước Giải Khát",
      "food_star": "4.5",
      "food_vote": "9999",
      "food_price": "10000.00",
      "food_discount": "0.00",
      "food_desc": "1 phần mỗi khẩu phần",
      "food_status": "best seller",
      "food_type": "Chay",
      "food_category": "Thức Uống",
      "food_src": "tu/tu6.png"
    }
  ]